services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather_coffee_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d weather_coffee_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: